splash = false
preload = /home/luca/.dotfiles/wallpapers/wp2.jpeg
wallpaper = DP-2,/home/luca/.dotfiles/wallpapers/wp2.jpeg
wallpaper = HDMI-A-1,/home/luca/.dotfiles/wallpapers/wp2.jpeg
wallpaper = eDP-1,/home/luca/.dotfiles/wallpapers/wp2.jpeg
