ZSH=/usr/share/oh-my-zsh/
ZSH_THEME="robbyrussell"
plugins=(sudo git rust node fd npm docker docker-compose command-not-found)

ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi
source $ZSH/oh-my-zsh.sh

export EDITOR=vim
export SHELL=zsh

alias l="exa -lh"
alias la="exa -lah"
alias lt="exa -lah --tree"
alias cat="bat"
alias cd="z"
alias mv="mv -v"
alias cp="cp -v"
alias rm="rm -v"
alias mkdir="mkdir -pv"
alias pacman="sudo pacman"

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(rtx activate zsh)"
eval "$(thefuck --alias)"
pfetch
