#!/bin/sh

# Check where the windows bootloader is and set it as the next boot target
# then reboot

sudo efibootmgr --bootnext $(sudo efibootmgr -v | awk 'match($0, /^Boot(.*)\* Windows/, ary) { print ary[1] }')
sudo reboot
